PATCH http://localhost:5000/api/v1/ideas/5c94201b81cf691a742c7e44/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzkzYmQxNjU5MTZlZTFiZDhjOTE1NzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NTMxOTM1NDAsImV4cCI6MTU1MzI3OTk0MH0.lPHeInUR9JiIaaZ4qt6MDuFBP0VOjR3QVIjW3JXxTs8